
-- ==========================================================
-- 1. إنشاء الجداول الأساسية
-- ==========================================================

-- جدول الإعدادات (Settings)
CREATE TABLE IF NOT EXISTS public.settings (
    id INT PRIMARY KEY DEFAULT 1,
    logo_url TEXT,
    hero_bg_url TEXT,
    site_title TEXT DEFAULT 'عصر الهامور',
    android_url TEXT DEFAULT '#',
    ios_url TEXT DEFAULT '#',
    is_maintenance_mode BOOLEAN DEFAULT FALSE,
    maintenance_message TEXT DEFAULT 'الموقع تحت الصيانة حالياً، سنعود قريباً!',
    showcase_images JSONB DEFAULT '{}'::jsonb,
    translations JSONB DEFAULT '{}'::jsonb,
    social_links JSONB DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- جدول ملفات المستخدمين (Profiles)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
    email TEXT,
    role TEXT DEFAULT 'user', -- 'admin' or 'user'
    display_name TEXT,
    avatar_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- جدول الأخبار (News)
CREATE TABLE IF NOT EXISTS public.news (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title TEXT NOT NULL,
    excerpt TEXT,
    thumbnail_url TEXT,
    category TEXT DEFAULT 'تحديث',
    date TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- جدول رسائل الدعم (Tickets)
CREATE TABLE IF NOT EXISTS public.tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    email TEXT,
    subject TEXT,
    message TEXT,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================================
-- 2. إعداد الـ Storage (Buckets)
-- ==========================================================

-- إنشاء الحاويات إذا لم تكن موجودة (تحتاج صلاحيات كافية)
INSERT INTO storage.buckets (id, name, public)
VALUES ('assets', 'assets', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public)
VALUES ('showcase', 'showcase', true)
ON CONFLICT (id) DO NOTHING;

-- سياسات الوصول للـ Storage
-- السماح للجميع بمشاهدة الملفات
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id IN ('assets', 'showcase'));

-- السماح للمشرفين فقط برفع وحذف الملفات
DROP POLICY IF EXISTS "Admin Upload" ON storage.objects;
CREATE POLICY "Admin Upload" ON storage.objects FOR INSERT WITH CHECK (
  bucket_id IN ('assets', 'showcase') AND 
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

DROP POLICY IF EXISTS "Admin Delete" ON storage.objects;
CREATE POLICY "Admin Delete" ON storage.objects FOR DELETE USING (
  bucket_id IN ('assets', 'showcase') AND 
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- ==========================================================
-- 3. إدخال البيانات الأولية (Initial Data)
-- ==========================================================

INSERT INTO public.settings (id, site_title)
VALUES (1, 'عصر الهامور')
ON CONFLICT (id) DO NOTHING;

-- ==========================================================
-- 4. وظيفة الربط التلقائي للمستخدمين (Triggers)
-- ==========================================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, display_name, role)
  VALUES (
    new.id, 
    new.email, 
    COALESCE(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1)), 
    CASE WHEN new.email = 'aaatay3@gmail.com' THEN 'admin' ELSE 'user' END
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ==========================================================
-- 5. تفعيل نظام الحماية (Row Level Security - RLS)
-- ==========================================================

ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;

-- السياسات الأساسية
CREATE POLICY "Public Read Settings" ON public.settings FOR SELECT USING (true);
CREATE POLICY "Admin All Settings" ON public.settings FOR ALL USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

CREATE POLICY "Public Read Profiles" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users Update Own Profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Admin All Profiles" ON public.profiles FOR ALL USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

CREATE POLICY "Public Read News" ON public.news FOR SELECT USING (true);
CREATE POLICY "Admin All News" ON public.news FOR ALL USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

CREATE POLICY "Public Insert Tickets" ON public.tickets FOR INSERT WITH CHECK (true);
CREATE POLICY "Admin All Tickets" ON public.tickets FOR ALL USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));
