
-- ==========================================
-- 1. ضمان وجود الجدول الأساسي
-- ==========================================
CREATE TABLE IF NOT EXISTS public.settings (
    id INT PRIMARY KEY DEFAULT 1
);

-- ==========================================
-- 2. إضافة الأعمدة بشكل منفصل (لتجنب تعارض الـ Transaction)
-- ==========================================
ALTER TABLE public.settings ADD COLUMN IF NOT EXISTS logo_url TEXT;
ALTER TABLE public.settings ADD COLUMN IF NOT EXISTS hero_bg_url TEXT;
ALTER TABLE public.settings ADD COLUMN IF NOT EXISTS site_title TEXT;
ALTER TABLE public.settings ADD COLUMN IF NOT EXISTS android_url TEXT;
ALTER TABLE public.settings ADD COLUMN IF NOT EXISTS ios_url TEXT;
ALTER TABLE public.settings ADD COLUMN IF NOT EXISTS is_maintenance_mode BOOLEAN DEFAULT FALSE;
ALTER TABLE public.settings ADD COLUMN IF NOT EXISTS maintenance_message TEXT;
ALTER TABLE public.settings ADD COLUMN IF NOT EXISTS showcase_images JSONB;
ALTER TABLE public.settings ADD COLUMN IF NOT EXISTS translations JSONB;
ALTER TABLE public.settings ADD COLUMN IF NOT EXISTS social_links JSONB;
ALTER TABLE public.settings ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- ==========================================
-- 3. إدخال الصف الأول (بشكل تدريجي)
-- ==========================================
-- أولاً: التأكد من وجود الصف رقم 1
INSERT INTO public.settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- ثانياً: تحديث القيم الافتراضية إذا كانت فارغة
UPDATE public.settings 
SET site_title = 'عصر الهامور', 
    is_maintenance_mode = FALSE 
WHERE id = 1 AND site_title IS NULL;

-- ==========================================
-- 4. إعداد الجداول الأخرى
-- ==========================================
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  email TEXT,
  role TEXT DEFAULT 'user', 
  display_name TEXT,
  avatar_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.news (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  title TEXT NOT NULL,
  excerpt TEXT,
  thumbnail_url TEXT,
  category TEXT,
  date TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  email TEXT,
  subject TEXT,
  message TEXT,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 5. الربط التلقائي للمستخدمين الجدد
-- ==========================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, display_name, role)
  VALUES (
    new.id, 
    new.email, 
    COALESCE(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1)), 
    CASE WHEN new.email = 'aaatay3@gmail.com' THEN 'admin' ELSE 'user' END
  )
  ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ==========================================
-- 6. تفعيل السياسات الأمنية
-- ==========================================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read Settings" ON public.settings;
CREATE POLICY "Public Read Settings" ON public.settings FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin All Settings" ON public.settings;
CREATE POLICY "Admin All Settings" ON public.settings FOR ALL USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

DROP POLICY IF EXISTS "Public Read News" ON public.news;
CREATE POLICY "Public Read News" ON public.news FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Insert Tickets" ON public.tickets;
CREATE POLICY "Public Insert Tickets" ON public.tickets FOR INSERT WITH CHECK (true);
