
-- ==========================================================
-- 1. الجداول الأساسية
-- ==========================================================

CREATE TABLE IF NOT EXISTS public.settings (
    id INT PRIMARY KEY DEFAULT 1,
    logo_url TEXT,
    hero_bg_url TEXT,
    site_title TEXT DEFAULT 'عصر الهامور',
    android_url TEXT DEFAULT '#',
    ios_url TEXT DEFAULT '#',
    is_maintenance_mode BOOLEAN DEFAULT FALSE,
    maintenance_message TEXT DEFAULT 'الأسطول في مهمة صيانة سريعة، سنعود قريباً!',
    qr_data TEXT DEFAULT '',
    custom_qr_url TEXT DEFAULT '',
    showcase_images JSONB DEFAULT '{}'::jsonb,
    translations JSONB DEFAULT '{}'::jsonb,
    social_links JSONB DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
    email TEXT,
    role TEXT DEFAULT 'user' CHECK (role IN ('admin', 'user')),
    display_name TEXT,
    avatar_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.news (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title TEXT NOT NULL,
    excerpt TEXT,
    thumbnail_url TEXT,
    category TEXT DEFAULT 'تحديث',
    date TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    email TEXT,
    subject TEXT,
    message TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================================
-- 2. إعداد الحماية والسياسات (RLS)
-- ==========================================================

ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Public Read Settings" ON public.settings;
    DROP POLICY IF EXISTS "Admin All Settings" ON public.settings;
    DROP POLICY IF EXISTS "Public Read News" ON public.news;
    DROP POLICY IF EXISTS "Admin All News" ON public.news;
    DROP POLICY IF EXISTS "Anyone can insert tickets" ON public.tickets;
    DROP POLICY IF EXISTS "Admin can see tickets" ON public.tickets;
    DROP POLICY IF EXISTS "Users can read own profile" ON public.profiles;
    DROP POLICY IF EXISTS "Admin can manage all profiles" ON public.profiles;

    CREATE POLICY "Public Read Settings" ON public.settings FOR SELECT USING (true);
    CREATE POLICY "Admin All Settings" ON public.settings FOR ALL USING (
      EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
    );

    CREATE POLICY "Public Read News" ON public.news FOR SELECT USING (true);
    CREATE POLICY "Admin All News" ON public.news FOR ALL USING (
      EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
    );

    CREATE POLICY "Anyone can insert tickets" ON public.tickets FOR INSERT WITH CHECK (true);
    CREATE POLICY "Admin can see tickets" ON public.tickets FOR SELECT USING (
      EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
    );

    CREATE POLICY "Users can read own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
    CREATE POLICY "Admin can manage all profiles" ON public.profiles FOR ALL USING (
      EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
    );
END $$;

-- ==========================================================
-- 3. التلقائية (Triggers)
-- ==========================================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role, display_name)
  VALUES (
    new.id, 
    new.email, 
    CASE WHEN LOWER(new.email) = 'aaatay3@gmail.com' THEN 'admin' ELSE 'user' END,
    COALESCE(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1))
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

INSERT INTO public.settings (id, site_title)
VALUES (1, 'عصر الهامور')
ON CONFLICT (id) DO NOTHING;
